// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.0
// source: internal/proto/analyzer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AIAnalyzer_AnalyzeRequest_FullMethodName = "/analyzer.AIAnalyzer/AnalyzeRequest"
)

// AIAnalyzerClient is the client API for AIAnalyzer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIAnalyzerClient interface {
	// AnalyzeRequest evaluates an incoming HTTP request for malicious intent,
	// prompt injection, and other AI-based risk factors.
	AnalyzeRequest(ctx context.Context, in *AnalyzeRequestMessage, opts ...grpc.CallOption) (*AnalyzeResponseMessage, error)
}

type aIAnalyzerClient struct {
	cc grpc.ClientConnInterface
}

func NewAIAnalyzerClient(cc grpc.ClientConnInterface) AIAnalyzerClient {
	return &aIAnalyzerClient{cc}
}

func (c *aIAnalyzerClient) AnalyzeRequest(ctx context.Context, in *AnalyzeRequestMessage, opts ...grpc.CallOption) (*AnalyzeResponseMessage, error) {
	out := new(AnalyzeResponseMessage)
	err := c.cc.Invoke(ctx, AIAnalyzer_AnalyzeRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIAnalyzerServer is the server API for AIAnalyzer service.
// All implementations must embed UnimplementedAIAnalyzerServer
// for forward compatibility
type AIAnalyzerServer interface {
	// AnalyzeRequest evaluates an incoming HTTP request for malicious intent,
	// prompt injection, and other AI-based risk factors.
	AnalyzeRequest(context.Context, *AnalyzeRequestMessage) (*AnalyzeResponseMessage, error)
	mustEmbedUnimplementedAIAnalyzerServer()
}

// UnimplementedAIAnalyzerServer must be embedded to have forward compatible implementations.
type UnimplementedAIAnalyzerServer struct {
}

func (UnimplementedAIAnalyzerServer) AnalyzeRequest(context.Context, *AnalyzeRequestMessage) (*AnalyzeResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeRequest not implemented")
}
func (UnimplementedAIAnalyzerServer) mustEmbedUnimplementedAIAnalyzerServer() {}

// UnsafeAIAnalyzerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIAnalyzerServer will
// result in compilation errors.
type UnsafeAIAnalyzerServer interface {
	mustEmbedUnimplementedAIAnalyzerServer()
}

func RegisterAIAnalyzerServer(s grpc.ServiceRegistrar, srv AIAnalyzerServer) {
	s.RegisterService(&AIAnalyzer_ServiceDesc, srv)
}

func _AIAnalyzer_AnalyzeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIAnalyzerServer).AnalyzeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIAnalyzer_AnalyzeRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIAnalyzerServer).AnalyzeRequest(ctx, req.(*AnalyzeRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// AIAnalyzer_ServiceDesc is the grpc.ServiceDesc for AIAnalyzer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIAnalyzer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analyzer.AIAnalyzer",
	HandlerType: (*AIAnalyzerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeRequest",
			Handler:    _AIAnalyzer_AnalyzeRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/analyzer.proto",
}
