# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyzer.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalyzer.proto\x12\x08\x61nalyzer\"\xd9\x01\n\x15\x41nalyzeRequestMessage\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x11\n\tclient_ip\x18\x02 \x01(\t\x12\x0e\n\x06method\x18\x03 \x01(\t\x12\x0c\n\x04path\x18\x04 \x01(\t\x12=\n\x07headers\x18\x05 \x03(\x0b\x32,.analyzer.AnalyzeRequestMessage.HeadersEntry\x12\x0c\n\x04\x62ody\x18\x06 \x01(\t\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"f\n\x16\x41nalyzeResponseMessage\x12\x12\n\nrisk_score\x18\x01 \x01(\x05\x12\x19\n\x11\x62lock_recommended\x18\x02 \x01(\x08\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\r\n\x05\x66lags\x18\x04 \x03(\t2c\n\nAIAnalyzer\x12U\n\x0e\x41nalyzeRequest\x12\x1f.analyzer.AnalyzeRequestMessage\x1a .analyzer.AnalyzeResponseMessage\"\x00\x42\x30Z.github.com/aegis/firewall/internal/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/aegis/firewall/internal/proto;proto'
  _globals['_ANALYZEREQUESTMESSAGE_HEADERSENTRY']._loaded_options = None
  _globals['_ANALYZEREQUESTMESSAGE_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_ANALYZEREQUESTMESSAGE']._serialized_start=29
  _globals['_ANALYZEREQUESTMESSAGE']._serialized_end=246
  _globals['_ANALYZEREQUESTMESSAGE_HEADERSENTRY']._serialized_start=200
  _globals['_ANALYZEREQUESTMESSAGE_HEADERSENTRY']._serialized_end=246
  _globals['_ANALYZERESPONSEMESSAGE']._serialized_start=248
  _globals['_ANALYZERESPONSEMESSAGE']._serialized_end=350
  _globals['_AIANALYZER']._serialized_start=352
  _globals['_AIANALYZER']._serialized_end=451
# @@protoc_insertion_point(module_scope)
