package proxy

import (
	"encoding/json"
	"errors"
	"net/http"
	"sync"
	"time"

	"github.com/sony/gobreaker"
)

// CircuitBreakerRegistry manages a thread-safe map of Circuit Breakers per Project.
type CircuitBreakerRegistry struct {
	mu       sync.RWMutex
	breakers map[string]*gobreaker.CircuitBreaker
}

// NewCircuitBreakerRegistry initializes the registry.
func NewCircuitBreakerRegistry() *CircuitBreakerRegistry {
	return &CircuitBreakerRegistry{
		breakers: make(map[string]*gobreaker.CircuitBreaker),
	}
}

// GetBreaker retrieves or creates a Circuit Breaker for the given project and configuration.
func (r *CircuitBreakerRegistry) GetBreaker(projectID string, route *RouteConfig) *gobreaker.CircuitBreaker {
	r.mu.RLock()
	cb, exists := r.breakers[projectID]
	r.mu.RUnlock()

	if exists {
		return cb
	}

	r.mu.Lock()
	defer r.mu.Unlock()

	// Double-checked locking
	if cb, exists = r.breakers[projectID]; exists {
		return cb
	}

	// Default Settings
	maxFailures := uint32(5)
	timeout := 30 * time.Second

	// Dynamically override from Security Rules if present
	if rawConfig, exists := route.SecurityRules["circuit_breaker"]; exists {
		var customConf struct {
			MaxFailures uint32 `json:"max_failures"`
			TimeoutSec  int    `json:"timeout"`
		}
		if err := json.Unmarshal(rawConfig, &customConf); err == nil {
			if customConf.MaxFailures > 0 {
				maxFailures = customConf.MaxFailures
			}
			if customConf.TimeoutSec > 0 {
				timeout = time.Duration(customConf.TimeoutSec) * time.Second
			}
		}
	}

	st := gobreaker.Settings{
		Name:        "cb-" + projectID,
		MaxRequests: 1,       // How many requests to allow when Half-Open to test recovery
		Interval:    0,       // Never clear counts (only reset on successful request)
		Timeout:     timeout, // How long to stay Open before transitioning to Half-Open
		ReadyToTrip: func(counts gobreaker.Counts) bool {
			return counts.ConsecutiveFailures >= maxFailures
		},
	}

	cb = gobreaker.NewCircuitBreaker(st)
	r.breakers[projectID] = cb
	return cb
}

// CircuitBreakerTransport wraps the default http.RoundTripper and intercepts errors.
type CircuitBreakerTransport struct {
	BaseTransport http.RoundTripper
	Registry      *CircuitBreakerRegistry
}

// RoundTrip executes the HTTP request inside the gobreaker state machine.
func (t *CircuitBreakerTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	// Extract the RouteConfig from the context (injected by RouteContextMiddleware)
	route, ok := req.Context().Value(RouteConfigKey).(*RouteConfig)
	if !ok || route == nil {
		// If context is missing, just fallback to base transport
		return t.BaseTransport.RoundTrip(req)
	}

	// Check if Circuit Breaker is explicitly disabled
	if rawConfig, exists := route.SecurityRules["circuit_breaker"]; exists {
		var customConf struct {
			Enabled *bool `json:"enabled"`
		}
		if err := json.Unmarshal(rawConfig, &customConf); err == nil {
			if customConf.Enabled != nil && !*customConf.Enabled {
				// Bypass Circuit Breaker entirely
				return t.BaseTransport.RoundTrip(req)
			}
		}
	}

	cb := t.Registry.GetBreaker(route.ProjectID, route)

	respInt, err := cb.Execute(func() (interface{}, error) {
		resp, err := t.BaseTransport.RoundTrip(req)
		
		// If there is a network error (Connection Refused, Timeout, DNS failure)
		if err != nil {
			return nil, err
		}

		// If the upstream responds with a 5xx Server Error (e.g., 502, 503, 504)
		if resp.StatusCode >= 500 {
			// We MUST return an error so gobreaker counts it as a failure!
			// We attach the response to the error so we can still return it to the client.
			return resp, errors.New("upstream server error")
		}

		return resp, nil
	})

	if err != nil {
		// If the error was our custom 5xx wrapper, unwrap the response and return it!
		// We still want the client to receive the 500/502 generated by the upstream,
		// but we wanted gobreaker to count it as a failure.
		if err.Error() == "upstream server error" && respInt != nil {
			return respInt.(*http.Response), nil
		}

		// If the circuit is Open, gobreaker returns ErrOpenState without executing the function.
		// We pass this error up so the ReverseProxy ErrorHandler can catch it.
		return nil, err
	}

	return respInt.(*http.Response), nil
}
